version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: car_rental
      POSTGRES_USER: car_rental
      POSTGRES_PASSWORD: car_rental
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U car_rental -d car_rental"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"   # smtp
      - "8025:8025"   # web ui

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 20

  app:
    build: .
    depends_on:
      - postgres
      - redis
      - mailhog
      - minio
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/car_rental
      SPRING_DATASOURCE_USERNAME: car_rental
      SPRING_DATASOURCE_PASSWORD: car_rental
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_MAIL_HOST: mailhog
      SPRING_MAIL_PORT: 1025
      MAIL_FROM: "noreply@car-rental.local"
      S3_ENDPOINT: http://minio:9000
      S3_REGION: us-east-1
      S3_BUCKET: car-rental
      S3_ACCESS_KEY: minioadmin
      S3_SECRET_KEY: minioadmin
      AUTH_SERVER_ISSUER: http://localhost:8080
      ADMIN_CLIENT_ID: car-rental-admin
      ADMIN_CLIENT_SECRET: admin-secret
      PUBLIC_CLIENT_ID: car-rental-public
      PUBLIC_CLIENT_SECRET: public-secret
    ports:
      - "8080:8080"
